# -*- coding: utf-8 -*-
"""ProjetoSimu.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zZGonlFlsgQV90OJsBKKq2TMdBz4w5aj
"""

# Simulador de Empréstimos/Financiamentos
# Prestação mensal não pode ser superior a 20% do salário ou o empréstimo será negado
nome_produto = [] # Lista dos nomes do produto
valor_produto = [] # Lista dos valores do produto
print('Bem vindo ao Simulador de empréstimos e financiamentos.')
print('-=-' * 20)
print('Lembre-se que a prestação mensal não pode ser superior a 20% do salário ou o empréstimo será negado')
while True:
    continuar = str(input('''
Pressione ENTER para calcular um empréstimo ou um financiamento.
Digite LISTAR para listar os empréstimos feitos anteriormente.
Digite SAIR para sair.
''')).upper()
    if continuar == '':
        nome = str(input('Digite o nome do produto: ')) # Exemplos: Carro, Casa, Financiamento 1, Financiamento 2
        valor = float(input('Digite o valor do produto: '))
        salario = float(input("Digite o seu salário: "))
        anos = int(input('Em quantos anos você irá pagar: '))
        meses = anos * 12
        prestacao = valor / meses
        if prestacao > salario * 0.2: # Prestação maior do que 20% do salário
            print('Empréstimo negado você não possui uma renda mensal suficiente')
        else: #Prestação menor que 20% do salário
            print(f'Empréstimo Concedido, O valor da prestação será de: R$ {prestacao:.2f} ')
            nome_produto.append(nome) # Adiciona a entrada de dados nas listas
            valor_produto.append(valor)
    elif continuar == 'LISTAR': # Mostra os produtos e seus respectivos valores em forma de dicionário
        produtos = dict(zip(nome_produto,valor_produto)) # Transforma as listas em um dicionário
        print(produtos)
    elif continuar == 'SAIR': # Sai do progmrama
        print('Você saiu do Simulador')
        break
    else: # Em caso das opções 
        print('Digite uma das opções')
        break